environment:
  nodejs_version: "8"

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install

test_script:
  - npm test
  - npm start build
  - npm start mobile.setup
  - npm start mobile.cordova.addbowser
  - npm start mobile.build
