USE [master]
GO

/****** Object:  Database [Hahn]    Script Date: 5/28/2020 12:27:39 PM ******/
CREATE DATABASE [Hahn]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Hahn', FILENAME = N'C:\Users\Abdullah\Hahn.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Hahn_log', FILENAME = N'C:\Users\Abdullah\Hahn_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Hahn] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Hahn].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Hahn] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Hahn] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Hahn] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Hahn] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Hahn] SET ARITHABORT OFF 
GO

ALTER DATABASE [Hahn] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Hahn] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Hahn] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Hahn] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Hahn] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Hahn] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Hahn] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Hahn] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Hahn] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Hahn] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Hahn] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Hahn] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Hahn] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Hahn] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Hahn] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Hahn] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Hahn] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Hahn] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Hahn] SET  MULTI_USER 
GO

ALTER DATABASE [Hahn] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Hahn] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Hahn] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Hahn] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Hahn] SET  READ_WRITE 
GO


